



fatal: [pi-02-ct]: FAILED! => {"failed": true, "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/briank/workspace/PyHouse-ansible/roles/node_red/tasks/backup-flows.yaml': line 35, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: BackupFlows-03 - Check flow into a git repository.
  ^ here


The error appears to have been in '/home/briank/workspace/PyHouse-ansible/roles/node_red/tasks/backup-flows.yaml': line 35, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: BackupFlows-03 - Check flow into a git repository.
  ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/briank/workspace/PyHouse-ansible/roles/node_red/tasks/backup-flows.yaml': line 35, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: BackupFlows-03 - Check flow into a git repository.
  ^ here
"}                                                                                                                                                                       
fatal: [pi-11-ct]: FAILED! => {"failed": true, "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/briank/workspace/PyHouse-ansible/roles/node_red/tasks/backup-flows.yaml': line 35, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: BackupFlows-03 - Check flow into a git repository.
  ^ here


The error appears to have been in '/home/briank/workspace/PyHouse-ansible/roles/node_red/tasks/backup-flows.yaml': line 35, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: BackupFlows-03 - Check flow into a git repository.
  ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/briank/workspace/PyHouse-ansible/roles/node_red/tasks/backup-flows.yaml': line 35, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: BackupFlows-03 - Check flow into a git repository.
  ^ here
"}                                                                                                                                                                       

